### ISSUE TITLE
Get SME Input After Regression Testing: AP Bio -Duplicate Questions

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2567] opened 2019-04-12 20:31 UTC
**SCENARIO** _Briefly describe the issue._

A couple of Duplicate Questions are found in AP Bio: 

153@5&219@3
152@4&218@4

same question, different IDs
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v ] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v ] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** student03
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v ] content 
- [ ] demo
- **OS:**
- [v ] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
66.0.2
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by openstaxalina** [comment] 2019-06-26 18:57
The questions are not exact duplicates - there are wording differences between most of the elements, except the question stem.  Therefore, we need subject matter export (SME) input to determine which assessment(s) to remove.  I can route these to a SME.  I will wait until we have compiled all items for SME review during regression testing.

**Comment by carlycurran** [comment] 2019-08-19 22:12
@openstaxalina do you want to see how this shakes out during the pilot? I think our timeframe for updating these questions has passed, so I say we wait for teacher feedback.

**Comment by openstaxalina** [comment] 2019-08-20 18:20
I opened errata for this:
https://openstax.org/errata/9270
https://openstax.org/errata/9271

I am going to close this issue since we use the errata tool to log and track errata.

**Closed by openstaxalina** 2019-08-20 18:20 UTC
Labels: bug
