### ISSUE TITLE
Assignment Due Date rendered as 02/32/2019 in Tutor

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2490] opened 2019-01-16 22:47 UTC
**SCENARIO** _Briefly describe the issue._

Assignment Due Date rendered as 02/32/2019 in Tutor

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

Signed in as instructor Sarah LeGresley and tried to edit the reading assignment on Feb 1st in her course Spring 2019 PHSX 114:College Physics I

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [ v] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [ ] Student  
- [v ] Teacher
- [ ] N/A
- **Username:** Sarah LeGresley 
- **URL:**  https://tutor.openstax.org/course/4804/reading/43123
- **Course number:**  PHSX 114:College Physics I
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ v] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [ ] content 
- [ ] demo
- **OS:**
- [ c] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [ v] Firefox 
- [ v] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

worked just as fine as 02/32/2019==02/01/2019 (mod 31)...
this problem appeared in multiple assignments
----------------
**Images or Screenshots** (_attach below_)
![6391547677128_.pic_hd.jpg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/1033246a-8c57-404c-84e2-aa3ceb082f75)

**Comment by nathanstitt** [comment] 2019-01-16 22:48
thanks, but this is a dupe of https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor-js/2486 which I just fixed :)

**Closed** 2019-01-18 16:03 UTC
Labels: bug
